// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegelIde.Data;

#nullable disable

namespace RegelIde.Data.Migrasjoner
{
    [DbContext(typeof(RegelIdeDbContext))]
    [Migration("20260723235150_MarkerVersjonSomConcurrencyToken")]
    partial class MarkerVersjonSomConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegelIde.Data.ProveniensEntitet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiForslagVersjon")
                        .HasColumnType("text")
                        .HasColumnName("ai_forslag_versjon");

                    b.Property<DateTimeOffset>("Dato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dato")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EndretAv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endret_av");

                    b.Property<Guid>("EntitetId")
                        .HasColumnType("uuid")
                        .HasColumnName("entitet_id");

                    b.Property<string>("EntitetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entitet_type");

                    b.Property<string>("GodkjentAv")
                        .HasColumnType("text")
                        .HasColumnName("godkjent_av");

                    b.Property<string>("Handling")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling");

                    b.Property<string>("KildeReferanserJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("kilde_referanser");

                    b.HasKey("Id")
                        .HasName("proveniens_pkey");

                    b.HasIndex("EntitetType", "EntitetId")
                        .HasDatabaseName("ix_proveniens_entitet");

                    b.ToTable("proveniens", (string)null);
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeEntitet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AknXml")
                        .HasColumnType("text")
                        .HasColumnName("akn_xml");

                    b.Property<string>("Doctype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctype");

                    b.Property<string>("Eli")
                        .HasColumnType("text")
                        .HasColumnName("eli");

                    b.Property<string>("Entitetsstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("gjeldende")
                        .HasColumnName("entitetsstatus");

                    b.Property<Guid?>("ErstatterId")
                        .HasColumnType("uuid")
                        .HasColumnName("erstatter_id");

                    b.Property<DateOnly?>("GyldigFra")
                        .HasColumnType("date")
                        .HasColumnName("gyldig_fra");

                    b.Property<DateOnly?>("GyldigTil")
                        .HasColumnType("date")
                        .HasColumnName("gyldig_til");

                    b.Property<DateOnly?>("Ikrafttredelse")
                        .HasColumnType("date")
                        .HasColumnName("ikrafttredelse");

                    b.Property<string>("Importrolle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("primaer")
                        .HasColumnName("importrolle");

                    b.Property<string>("Kildetype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kildetype");

                    b.Property<DateOnly?>("KonsolidertDato")
                        .HasColumnType("date")
                        .HasColumnName("konsolidert_dato");

                    b.Property<string>("Kortnavn")
                        .HasColumnType("text")
                        .HasColumnName("kortnavn");

                    b.Property<string>("OpprettetAv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opprettet_av");

                    b.Property<DateTimeOffset>("OpprettetTidspunkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opprettet_tidspunkt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SistEndretAv")
                        .HasColumnType("text")
                        .HasColumnName("sist_endret_av");

                    b.Property<DateTimeOffset?>("SistEndretTidspunkt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sist_endret_tidspunkt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tittel");

                    b.Property<string>("Utgiver")
                        .HasColumnType("text")
                        .HasColumnName("utgiver");

                    b.Property<int>("Versjon")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versjon");

                    b.HasKey("Id")
                        .HasName("rettskilder_pkey");

                    b.HasIndex("Eli")
                        .IsUnique()
                        .HasDatabaseName("ux_rettskilder_eli_gjeldende")
                        .HasFilter("entitetsstatus = 'gjeldende'");

                    b.HasIndex("ErstatterId");

                    b.ToTable("rettskilder", null, t =>
                        {
                            t.HasCheckConstraint("ck_rettskilder_akn_xml", "importrolle = 'referanse' OR akn_xml IS NOT NULL");

                            t.HasCheckConstraint("ck_rettskilder_importrolle", "importrolle IN ('primaer', 'referanse')");
                        });
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeNodeEntitet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Eid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eid");

                    b.Property<string>("KildeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kilde_id");

                    b.Property<string>("Kildesystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("lovdata")
                        .HasColumnName("kildesystem");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_type");

                    b.Property<string>("Nummer")
                        .HasColumnType("text")
                        .HasColumnName("nummer");

                    b.Property<string>("OffisiellEli")
                        .HasColumnType("text")
                        .HasColumnName("offisiell_eli");

                    b.Property<string>("Overskrift")
                        .HasColumnType("text")
                        .HasColumnName("overskrift");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("uuid")
                        .HasColumnName("rettskilde_id");

                    b.Property<int>("Sorteringsrekkefolge")
                        .HasColumnType("integer")
                        .HasColumnName("sorteringsrekkefolge");

                    b.Property<string>("Tekst")
                        .HasColumnType("text")
                        .HasColumnName("tekst");

                    b.Property<string>("TekstHash")
                        .HasColumnType("text")
                        .HasColumnName("tekst_hash");

                    b.HasKey("Id")
                        .HasName("rettskilde_noder_pkey");

                    b.HasIndex("ParentNodeId")
                        .HasDatabaseName("ix_rettskilde_noder_parent");

                    b.HasIndex("Eid", "TekstHash")
                        .HasDatabaseName("ix_rettskilde_noder_eid_hash");

                    b.HasIndex("RettskildeId", "Eid")
                        .IsUnique()
                        .HasDatabaseName("rettskilde_noder_rettskilde_id_eid_key");

                    b.ToTable("rettskilde_noder", (string)null);
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeReferanseEntitet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FraNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fra_node_id");

                    b.Property<string>("TilEid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("til_eid");

                    b.Property<Guid>("TilRettskildeId")
                        .HasColumnType("uuid")
                        .HasColumnName("til_rettskilde_id");

                    b.HasKey("Id")
                        .HasName("rettskilde_referanser_pkey");

                    b.HasIndex("TilRettskildeId");

                    b.HasIndex("FraNodeId", "TilRettskildeId", "TilEid")
                        .IsUnique()
                        .HasDatabaseName("rettskilde_referanser_fra_node_id_til_rettskilde_id_til_ei_key");

                    b.ToTable("rettskilde_referanser", (string)null);
                });

            modelBuilder.Entity("RegelIde.Data.TekstTaggEntitet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<string>("Entitetsstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("gjeldende")
                        .HasColumnName("entitetsstatus");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("NodeEid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_eid");

                    b.Property<string>("NodeTekstHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_tekst_hash");

                    b.Property<string>("OpprettetAv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opprettet_av");

                    b.Property<DateTimeOffset>("OpprettetTidspunkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opprettet_tidspunkt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("QuoteExact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_exact");

                    b.Property<string>("QuotePrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_prefix");

                    b.Property<string>("QuoteSuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_suffix");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<Guid>("RettskildeId")
                        .HasColumnType("uuid")
                        .HasColumnName("rettskilde_id");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.HasKey("Id")
                        .HasName("tekst_tagger_pkey");

                    b.HasIndex("RettskildeId", "NodeEid")
                        .HasDatabaseName("ix_tekst_tagger_node");

                    b.HasIndex("RettskildeId", "NodeEid", "StartOffset", "EndOffset", "Kind", "RefId")
                        .IsUnique()
                        .HasDatabaseName("tekst_tagger_unik_tagg");

                    b.ToTable("tekst_tagger", (string)null);
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeEntitet", b =>
                {
                    b.HasOne("RegelIde.Data.RettskildeEntitet", null)
                        .WithMany()
                        .HasForeignKey("ErstatterId");
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeNodeEntitet", b =>
                {
                    b.HasOne("RegelIde.Data.RettskildeNodeEntitet", null)
                        .WithMany()
                        .HasForeignKey("ParentNodeId");

                    b.HasOne("RegelIde.Data.RettskildeEntitet", null)
                        .WithMany("Noder")
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeReferanseEntitet", b =>
                {
                    b.HasOne("RegelIde.Data.RettskildeNodeEntitet", null)
                        .WithMany()
                        .HasForeignKey("FraNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegelIde.Data.RettskildeEntitet", null)
                        .WithMany()
                        .HasForeignKey("TilRettskildeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegelIde.Data.TekstTaggEntitet", b =>
                {
                    b.HasOne("RegelIde.Data.RettskildeEntitet", null)
                        .WithMany()
                        .HasForeignKey("RettskildeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegelIde.Data.RettskildeEntitet", b =>
                {
                    b.Navigation("Noder");
                });
#pragma warning restore 612, 618
        }
    }
}
